name: Build & Run Checks

on:
  workflow_call:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies
        run: npm ci

  lint:
    needs: setup
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  build:
    needs: setup
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
